# general settings
name: train_HAT-S_SRx2_from_scratch
model_type: HATModel
scale: 2
num_gpu: 0
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: NTIRE
    type: PairedImageDataset
    dataroot_gt: datasets/Train/HR
    dataroot_lq: datasets/Train/LR_x2
    meta_info_file: hat/data/meta_info/meta_info_NTIRE23_GT.txt
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/HR
    dataroot_lq: datasets/Set5/image_SRF_2
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/HR
    dataroot_lq: datasets/Set14/image_SRF_2
    io_backend:
      type: disk

  val_3:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/urban100/HR
    dataroot_lq: datasets/urban100/image_SRF_2
    io_backend:
      type: disk


# network structures
network_g:
  type: HAT
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 24
  squeeze_factor: 24
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 144
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  sam_opt:
    type: SAMLoss
    loss_weight: 1.0
    criterion: l2
    sam_checkpoint: experiments\pretrained_models\sam_vit_h_4b8939.pth
    model_type: vit_h

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
